branches:
  only:
    - ci
language: rust
cache: cargo
matrix:
  include:
    - name: "Windows 32bit"
      rust: nightly-i686-pc-windows-msvc
      script: cargo build --all --release
      os: windows
    - name: "Windows 64bit"
      rust: nightly
      script: cargo build --all --release
      os: windows
    - name: "macOS"
      rust: nightly
      script: cargo build --all --release
      os: osx
