[package]
name = "yyx-data"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
yyx-utils = { path = "../yyx-utils" }
yyx-types = { path = "../yyx-types" }
log = "0.4"
failure = "0.1"
failure_derive = "0.1"
serde_json = "1.0"