[package]
name = "yyx"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
yyx-data = { path = "../../yyx-data" }
yyx-types = { path = "../../yyx-types" }
yyx-resources = { path = "../../yyx-resources" }
rocket = "0.4.0"
rocket_contrib = "0.4.0"
log = "0.4"
fern = "0.5"
chrono = "0.4"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }

[build-dependencies]
winres = "0.1.8"